id = "retropc-theme"
name = "RetroPC"
schema_version = 1
version = "0.0.1"
authors = ["Abhishek Bhatkar <bhatkar.abhishek80@gmail.com>"]
description = "Amber CRT RetroPC theme for Zed"
repository = "https://github.com/abhishek-bhatkar/retroPC-zed-theme"
